version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "{{cookiecutter.project_slug}}/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "{{cookiecutter.project_slug}}/frontend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "{{cookiecutter.project_slug}}/frontend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "{{cookiecutter.project_slug}}/backend/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "{{cookiecutter.project_slug}}/backend/"
    schedule:
      interval: "daily"
