version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/frontend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/backend/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "daily"
    # Limited to 1 open PR at a time
    # This avoids the cycle of 4 open PRs, merge 1, Dependabot rebases the rest
    open-pull-requests-limit: 1
